### ISSUE TITLE
Implement xk6-webcrypto

### ISSUE THREAD

**Issue by oleiade** [grafana/xk6-webcrypto#16]
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/xk6-webcrypto/issues/15
- [ ] https://github.com/grafana/xk6-webcrypto/issues/14
- [ ] https://github.com/grafana/xk6-webcrypto/issues/31
- [ ] https://github.com/grafana/xk6-webcrypto/issues/11
- [ ] https://github.com/grafana/xk6-webcrypto/issues/10
- [ ] https://github.com/grafana/xk6-webcrypto/issues/30
- [x] https://github.com/grafana/xk6-webcrypto/issues/8
- [ ] https://github.com/grafana/xk6-webcrypto/issues/7
- [ ] https://github.com/grafana/xk6-webcrypto/issues/6
- [ ] https://github.com/grafana/xk6-webcrypto/issues/32
- [ ] https://github.com/grafana/xk6-webcrypto/issues/3
- [x] https://github.com/grafana/xk6-webcrypto/issues/17
- [ ] https://github.com/grafana/xk6-webcrypto/issues/18
- [x] https://github.com/grafana/xk6-webcrypto/issues/19
- [x] https://github.com/grafana/xk6-webcrypto/issues/20
```

**Comment by oleiade** [comment]
As we have implemented a large part of the API already, we will be closing this overarching issue in favor of more granular ones.
